finalists:
  - preprocessing: srad_nopad
    arch: densenet121
    hpo_dir: results/finetune_hpo/srad_nopad_densenet121/densenet121
    external_auc: 0.942
  - preprocessing: srad_nopad
    arch: convnext_tiny
    hpo_dir: results/finetune_hpo/srad_nopad_convnext_tiny/convnext_tiny
    external_auc: 0.9403
  - preprocessing: gauss_nopad
    arch: vit_base
    hpo_dir: results/finetune_hpo/gauss_nopad_vit_base/vit_base
    external_auc: 0.9385
